- .github/workflows/ci.yml
> Revert "Remove gh actions"

- docs/index.md
Change the link and wording for Everest a bit
> Update index.md - Everest link and wording

- mkdocs.yml
> DOCS-136 Create documentation project for Ivee

- docs/percona-for-postgresql.md
modified:   docs/percona-for-postgresql.md
> PG-1025 Updated redirects for PG product page to point to latest doc version

- docs/blog/index.md
modified:   docs/blog/index.md
> docs-142 - update Home paragraph

- docs/blog/posts/MySQL/percona-server-8.0.40-31-release.md
new file:   docs/blog/posts/MySQL/percona-server-8.0.40-31-release.md
> DOCS-PS-9472 Add announcement

- docs/blog/posts/MySQL/get-help.md
modified:   docs/blog/posts/MySQL/get-help.md
> DOCS-142 remove get help tag

- docs/css/extra.css
- docs/js/hide-back-to-index.js
- mkdocs.yml
modified:   docs/css/extra.css
new file:   docs/js/hide-back-to-index.js
modified:   mkdocs.yml
> DOCS-142 Remove Back to index button from plugin

- docs/new/get-help.md
- mkdocs.yml
- overrides/partials/banner.html
renamed:    docs/new/posts/MySQL/get-help.md -> docs/new/get-help.md
modified:   mkdocs.yml
modified:   overrides/partials/banner.html
> Update get help section

- docs/new/posts/Percona Monitoring and Management/pmm-3.0.0-beta.md
- docs/pmm.md
> Fix broken links in PMM announcement

- docs/new/posts/MySQL/percona-xtradb-cluster-8.4.3-3-released.md
new file:   docs/new/posts/MySQL/percona-xtradb-cluster-8.4.3-3-released.md
> PXC-4535 Add PXC 8.4.3-3 release announcement

- docs/new/posts/MySQL/pdpxc-8.0.40-release.md
new file:   docs/new/posts/MySQL/pdpxc-8.0.40-release.md
> DISTMYSQL-502 PDPXC 8.0.40 announcement

- docs/css/design.css
> DOCS-135 Fix the colour of the search results in dark mode

- docs/new/posts/MongoDB/pbm-2.9.0-release.md
- docs/new/posts/MongoDB/psmdb-6.0.2-17-release.md
- docs/new/posts/MongoDB/psmdb-6.0.20-17-release.md
- docs/new/posts/MongoDB/psmdb-7.0.16-10-release.md
- docs/new/posts/MongoDB/psmdb-8.0.4-2-release.md
new file:   docs/new/posts/MongoDB/pbm-2.9.0-release.md
new file:   docs/new/posts/MongoDB/psmdb-6.0.2-17-release.md
new file:   docs/new/posts/MongoDB/psmdb-7.0.16-10-release.md
new file:   docs/new/posts/MongoDB/psmdb-8.0.4-2-release.md
> PBM-1471 Added PBM and all PSMDB release announcements

- docs/new/posts/MySQL/percona-server-mysql-5.7.44-53-release.md
new file:   docs/new/posts/MySQL/percona-server-mysql-5.7.44-53-release.md
> Adding 5.7.44-53 announcement

- docs/new/posts/MySQL/pdps-8.0.41-release.md
- docs/new/posts/MySQL/percona-server-8.0.41-32-release.md
new file:   docs/new/posts/MySQL/pdps-8.0.41-release.md
new file:   docs/new/posts/MySQL/percona-server-8.0.41-32-release.md
> PS-9499 PS and PDPS announcements

- docs/new/index.md
- docs/new/posts/MySQL/clone-sst.md
- docs/new/posts/MySQL/pdpxc-8.0.41-release.md
- docs/new/posts/MySQL/percona-xtradb-cluster-8.0.41-32-release.md
modified:   docs/new/index.md
new file:   docs/new/posts/MySQL/clone-sst.md
new file:   docs/new/posts/MySQL/pdpxc-8.0.41-release.md
new file:   docs/new/posts/MySQL/percona-xtradb-cluster-8.0.41-32-release.md
> Add release and feature announcemnts for PXC and PDPXC 8.0.41

- docs/new/posts/Percona Operators/operator-for-postgresql-2.6.0.md
new file:   docs/new/posts/Percona Operators/operator-for-postgresql-2.6.0.md
> K8SPG-651 Added PG 2.6.0 announcement

- docs/new/posts/MySQL/clone-sst.md
- docs/new/posts/MySQL/percona-xtradb-cluster-5.7.44-31.65.6-release.md
modified:   docs/new/posts/MySQL/clone-sst.md
new file:   docs/new/posts/MySQL/percona-xtradb-cluster-5.7.44-31.65.6-release.md
> Add PXC 5.7.44-31.65.6 and update Clone for SST material

- docs/new/posts/MySQL/pdps-8.4.4-release.md
- docs/new/posts/MySQL/percona-server-8.4.4-4-release.md
new file:   docs/new/posts/MySQL/pdps-8.4.4-release.md
new file:   docs/new/posts/MySQL/percona-server-8.4.4-4-release.md
> DISTMYSQL-509/PS-9590 Add PS and PDPS release announcements

- docs/new/posts/MongoDB/pbm-2.9.1-release.md
new file:   docs/new/posts/MongoDB/pbm-2.9.1-release.md
> PBM-1527 Announced PBM 2.9.1

- docs/new/index.md
> updated featured announcements

- docs/new/.authors.yml
modified:   docs/new/.authors.yml
> Add a new author

- docs/new/index.md
- docs/new/posts/Percona Everest/openshift_support.md
Include an announcement regarding support for OpenShift in Percona Everest.
> add_openshift_support_everest

- docs/new/posts/Percona Operators/operator-for-xtradb-cluster-1.17.0.md
new file:   docs/new/posts/Percona Operators/operator-for-xtradb-cluster-1.17.0.md
>  K8SPG-1602-PXCO-1.17.0 announcement

- docs/new/posts/MySQL/pdpxc-8.4.3-release.md
- docs/new/posts/MySQL/pdpxc-8.4.4-release.md
- docs/new/posts/MySQL/percona-xtradb-cluster-8.4.4-4-released.md
modified:   docs/new/posts/MySQL/pdpxc-8.4.3-release.md
new file:   docs/new/posts/MySQL/pdpxc-8.4.4-release.md
new file:   docs/new/posts/MySQL/percona-xtradb-cluster-8.4.4-4-released.md
> PXC-4599 Add PCX/PDPX 8.4.4 release announcements

- docs/new/posts/Percona Toolkit/percona-toolkit-v3.6.0-release.md
- docs/new/posts/Percona Toolkit/percona-toolkit-v3.7.0-1-release.md
- docs/new/posts/Percona Toolkit/percona-toolkit-v3.7.0-release.md
modified:   docs/new/posts/Percona Toolkit/percona-toolkit-v3.6.0-release.md
new file:   docs/new/posts/Percona Toolkit/percona-toolkit-v3.7.0-1-release.md
modified:   docs/new/posts/Percona Toolkit/percona-toolkit-v3.7.0-release.md
> PT 3.7.0-1 announcement

- docs/new/posts/MySQL/percona-server-8.0.41-32-release.md
- docs/new/posts/MySQL/percona-server-8.0.42-33-release.md
new file:   docs/new/posts/MySQL/pdpxc-8.0.42-release.md
modified:   docs/new/posts/MySQL/percona-server-8.0.41-32-release.md
new file:   docs/new/posts/MySQL/percona-server-8.0.42-33-release.md
> PS-9735 Release 8.0.42-33 announcement

- docs/new/posts/MySQL/pdps-8.0.42-release.md
new file:   docs/new/posts/MySQL/pdps-8.0.42-release.md
> DISTMYSQL-522 PDPS 8.0.42 announcement

- docs/new/posts/PostgreSQL/pg-tde-rc2-release.md
- docs/new/posts/PostgreSQL/postgresql-17.5.1-release.md
new files added for PG 17.5.1 and pg_tde RC2 updates
> PG-17.5.1 announcement (pg_tde bundled)

- docs/new/posts/MySQL/pdps-8.4.5-release.md
new file:   docs/new/posts/MySQL/pdps-8.4.5-release.md
> DISTMYSQL-523 [DOC] Release notes for PDPS 8.4.5 announcement

- docs/percona-for-postgresql.md
updated the title of the pg_tde card by adding for PostrgreSQL at the end there
> Updated title card for pg_tde

- docs/new/posts/MySQL/percona-xtradb-cluster-8.0.42-33-release.md
new file:   docs/new/posts/MySQL/percona-xtradb-cluster-8.0.42-33-release.md
> PXC-4672 Percona XtraDB Cluster 8.0.42-33 announcement

- docs/new/posts/MySQL/percona-xtradb-cluster-5.7.44-31-65.4-release.md
- docs/new/posts/MySQL/percona-xtradb-cluster-5.7.44-31.65.5-release.md
- docs/new/posts/MySQL/percona-xtradb-cluster-5.7.44-31.65.6-release.md
- docs/new/posts/MySQL/percona-xtradb-cluster-5.7.44-31.65.7-release.md
modified:   docs/new/posts/MySQL/percona-xtradb-cluster-5.7.44-31-65.4-release.md
modified:   docs/new/posts/MySQL/percona-xtradb-cluster-5.7.44-31.65.5-release.md
modified:   docs/new/posts/MySQL/percona-xtradb-cluster-5.7.44-31.65.6-release.md
new file:   docs/new/posts/MySQL/percona-xtradb-cluster-5.7.44-31.65.7-release.md
> PXC-4669 Percona XtraDB Cluster 5.7.44-31.65.7 announcement

- docs/new/index.md
Also organized dates for the cards correctly in order
> Reorganize order of pg tde announcement to be at the top

- docs/new/posts/MySQL/percona-xtradb-cluster-8.4.5-5-released.md
modified:   docs/new/posts/MySQL/percona-xtradb-cluster-8.0.42-33-release.md
new file:   docs/new/posts/MySQL/percona-xtradb-cluster-8.4.5-5-released.md
> PXC-4677 PXC 8.4.5-5 release announcement (8.0)

- docs/new/posts/MySQL/pdpxc-8.4.5-release.md
new file:   docs/new/posts/MySQL/pdpxc-8.4.5-release.md
> DISTMYSQL-529 [Doc] Release notes for - PDPXC 8.4.5

- docs/new/posts/MySQL/percona-xtradb-cluster-8.4.5-5-released.md
Update percona-xtradb-cluster-8.4.5-5-released.md
> Remove MyRocks info (PXC)

- docs/new/index.md
- docs/new/posts/Percona Everest/data_importers.md
- docs/new/posts/Percona Everest/everest-1.8.0-release.md
Add announcements for Everest release 1.8.0
> Evererst rel 1.8.0

- docs/new/index.md
- docs/percona-everest.md
- docs/percona-for-mongodb.md
- docs/percona-for-mysql.md
- docs/percona-for-postgresql.md
- docs/percona-lab.md
- docs/percona-operators.md
- docs/percona-utilities.md
- docs/pmm.md
modified:   docs/new/index.md
modified:   docs/percona-everest.md
modified:   docs/percona-for-mongodb.md
modified:   docs/percona-for-mysql.md
modified:   docs/percona-for-postgresql.md
modified:   docs/percona-lab.md
modified:   docs/percona-operators.md
modified:   docs/percona-utilities.md
modified:   docs/pmm.md
> DOCS-183 Remove the arrows from buttons on the Home page

- docs/css/extra.css
- mkdocs.yml
> DOCS-184 Fix "What's new" broken alignment 

- docs/new/posts/MySQL/percona-xtrabackup-8.0.35-34.release.md
Update percona-xtrabackup-8.0.35-34.release.md
> Remove RHEL 10 support

- docs/new/posts/MySQL/percona-server-8.0.43-34-release.md
new file:   docs/new/posts/MySQL/percona-server-8.0.43-34-release.md
> PS-10043 Add the PS 8.0.43-34 release announcement

- docs/new/posts/MySQL/pdps-8.0.43-release.md
new file:   docs/new/posts/MySQL/pdps-8.0.43-release.md
> DISTMYSQL-532 Release announcement for PDPS 8.0.43

- docs/new/posts/MySQL/percona-server-8.4.6-6-release.md
new file:   docs/new/posts/MySQL/percona-server-8.4.6-6-release.md
> PS-10048 Release announcement for PS 8.4.6-6

- docs/new/posts/MySQL/pdps-8.4.6-release.md
new file: docs/new/posts/MySQL/pdps-8.4.6-release.md
> DISTMYSQL-540 Release announcement for PDPS 8.4.6

- docs/new/posts/MongoDB/pbm-2.11.0-release.md
new file:   docs/new/posts/MongoDB/pbm-2.11.0-release.md
> PBM-1616 Announced PBM 2.11.0

- docs/new/posts/MySQL/pdpxc-8.4.6-release.md
new file:   docs/new/posts/MySQL/pdpxc-8.4.6-release.md
> DISTMYSQL-547 PDPXC 8.4.6 release announcement
